export { Header } from "../../../common/customer/Header/Header.jsx";
export { GenreCard } from '../../../common/customer/GenreCards/GenreCard.jsx';
export { NewArrivals } from "../../../common/customer/NewArrivals/NewArrival.jsx";
export { ProductCard } from "../../../common/customer/Card/ProductCard.jsx";
export { HorizontalProductCard } from "../../../common/customer/HorizontalCard/HorizontalProductCard.jsx";
export { Footer } from "../../../common/customer/Footer/Footer.jsx";
export { Sidebar } from '../../../common/customer/Sidebar/Sidebar.jsx';
export { Toast } from '../../../common/customer/Toast/Toast.jsx';
export { ShoppingBill } from '../../../common/customer/ShoppingBill/ShoppingBill.jsx';
export { WishlistProductCard } from '../../../common/customer/WishlistProductCard/WishlistProductCard.jsx';
// export { ProductOrderCard } from '../../../ProductOrderCard/ProductOrderCard';
export { Pagination } from '../../../common/customer/Pagination/Pagination.jsx';

export { Home } from "../Home/Home.jsx";
// export { Login } from "../../../Pages/AuthenticationPages/Login";
// export { Signup } from "../../../Pages/AuthenticationPages/Signup";
export { ProductPage } from "../ProductPage/ProductPage.jsx";
export { Shop } from "../Shop/Shop.jsx";
export { Wishlist } from "../Wishlist/Wishlist.jsx";
export { Cart } from "../Cart/Cart.jsx";
// export { Orders } from "../../../layouts/customer/Orders/Orders";