export const Errors = {
    required: ':field is required',
    minLength: ':field must be min {error} characters',
    maxLength: ':field must be max {error} characters',
    email: ':field is not correct format for email',
    phoneNumber: ':field must be 10 digits and start with 0',
    pattern: ':field is not correct format',
    password: ':field must contain at least one number, one letter and one special character',
    youtubeLink: ':field is not correct',
    isbn: ':field is not correct format',
    price: ':field must be a number',
    maxNumber: ':field must be less than {error}',
    minNumber: ':field must be higher than {error}',
    validDate: ':field is not correct format of date',
    pastDate: ':field must be a past date',
    status: ':field must be active or inactive',
    integer: ':field must be an integer',
}